(function(){const QR_LIB_URL="https://cdn.jsdelivr.net/npm/qrcode-generator@1.4.4/qrcode.min.js";state.qrLibraryPromise=state.qrLibraryPromise||null;function ensureQrLibrary(){return window.qrcode?Promise.resolve():(state.qrLibraryPromise||(state.qrLibraryPromise=new Promise((resolve,reject)=>{const existing=document.querySelector('script[src="'+QR_LIB_URL+'"]'),fail=()=>{state.qrLibraryPromise=null,reject(new Error("\u0E42\u0E2B\u0E25\u0E14 QR library \u0E44\u0E21\u0E48\u0E2A\u0E33\u0E40\u0E23\u0E47\u0E08"))};if(existing){existing.addEventListener("load",()=>window.qrcode?resolve():fail(),{once:!0}),existing.addEventListener("error",fail,{once:!0});return}const s=document.createElement("script");s.src=QR_LIB_URL,s.async=!0,s.onload=()=>window.qrcode?resolve():fail(),s.onerror=fail,document.head.appendChild(s)})),state.qrLibraryPromise)}function buildQrSvg(text,options){const opts=options||{},ec=opts.errorCorrection||"M",margin=opts.margin==null?2:opts.margin,qr=window.qrcode(0,ec);qr.addData(String(text)),qr.make();const count=qr.getModuleCount(),size=count+margin*2;let path="";for(let r=0;r<count;r++)for(let c=0;c<count;c++)qr.isDark(r,c)&&(path+="M"+(c+margin)+" "+(r+margin)+"h1v1h-1z");return'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 '+size+" "+size+`" shape-rendering="crispEdges" preserveAspectRatio="xMidYMid meet" width="100%" height="100%">
        <rect width="`+size+'" height="'+size+`" fill="#ffffff"/>
        <path d="`+path+`" fill="#0f172a"/>
      </svg>`}async function renderQrInto(container,text){await ensureQrLibrary(),container.innerHTML=buildQrSvg(text)}state.currentQr=null;async function openQrModal(assetId){const id=String(assetId||"");if(id){$("qrAssetTag").textContent="-",$("qrAssetName").textContent="-",$("qrAssetType").textContent="-",$("qrAssetSerial").textContent="-",$("qrUrlText").textContent="\u0E01\u0E33\u0E25\u0E31\u0E07\u0E42\u0E2B\u0E25\u0E14...",$("qrPreview").innerHTML="",openModal("qrModal");try{const json=await run("getAssetQrDataJson",id),data=typeof json=="string"?JSON.parse(json):json;if(!data||!data.ok)throw new Error(data&&data.error?data.error:"\u0E42\u0E2B\u0E25\u0E14 QR \u0E44\u0E21\u0E48\u0E2A\u0E33\u0E40\u0E23\u0E47\u0E08");const a=data.asset||{};$("qrAssetTag").textContent=a.asset_tag||"-",$("qrAssetName").textContent=a.computer_name||"-",$("qrAssetType").textContent=a.device_type||"-",$("qrAssetSerial").textContent=a.serial_number||"-",$("qrUrlText").textContent=data.qr_url,await renderQrInto($("qrPreview"),data.qr_url),state.currentQr={asset:a,qrUrl:data.qr_url}}catch(err){$("qrUrlText").textContent=err.message||String(err),toast(err.message||String(err))}}}function copyCurrentQrUrl(){if(!state.currentQr)return;const text=state.currentQr.qrUrl||"";text&&(navigator.clipboard&&navigator.clipboard.writeText?navigator.clipboard.writeText(text).then(()=>toast("\u0E04\u0E31\u0E14\u0E25\u0E2D\u0E01\u0E41\u0E25\u0E49\u0E27"),()=>fallbackCopy(text)):fallbackCopy(text))}function fallbackCopy(text){const ta=document.createElement("textarea");ta.value=text,ta.style.position="fixed",ta.style.left="-9999px",document.body.appendChild(ta),ta.select();try{document.execCommand("copy"),toast("\u0E04\u0E31\u0E14\u0E25\u0E2D\u0E01\u0E41\u0E25\u0E49\u0E27")}catch(e){toast("\u0E04\u0E31\u0E14\u0E25\u0E2D\u0E01\u0E44\u0E21\u0E48\u0E2A\u0E33\u0E40\u0E23\u0E47\u0E08")}ta.remove()}function downloadCurrentQr(){if(!state.currentQr)return;const svg=$("qrPreview").querySelector("svg");if(!svg)return;const tag=state.currentQr.asset.asset_tag||"asset",blob=new Blob([svg.outerHTML],{type:"image/svg+xml;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url,a.download="BNH-ITAM-QR-"+tag+".svg",a.click(),setTimeout(()=>URL.revokeObjectURL(url),1e3)}function printCurrentQr(){if(!state.currentQr)return;const a=state.currentQr.asset,svg=$("qrPreview").querySelector("svg");if(!svg)return;const w=window.open("","_blank","width=420,height=560");if(!w)return toast("Browser \u0E1A\u0E25\u0E47\u0E2D\u0E01 popup");w.document.write("<!doctype html><html><head><title>QR "+escapeHtml(a.asset_tag||"")+`</title>
<style>body{font-family:Arial,sans-serif;margin:0;padding:18px;color:#0f172a;text-align:center}
.label{display:inline-block;border:1px solid #d8e2ea;padding:14px;width:280px}
.qr{width:220px;height:220px;margin:0 auto}
h1{font-size:18px;margin:10px 0 4px;word-break:break-word}
.meta{font-size:12px;color:#64748b;margin:2px 0}</style></head><body>
<div class="label"><div class="qr">`+svg.outerHTML+`</div>
<h1>`+escapeHtml(a.asset_tag||"-")+`</h1>
<div class="meta">`+escapeHtml(a.computer_name||"-")+`</div>
<div class="meta">`+escapeHtml(a.device_type||"-")+" \xB7 "+escapeHtml(a.serial_number||"-")+`</div></div>
<script>window.onload=function(){window.print()};<\/script></body></html>`),w.document.close()}state.printLabels=null;async function openPrintLabelsForSelected(){const ids=selectedManagedAssetIds();if(!ids.length)return toast("\u0E40\u0E25\u0E37\u0E2D\u0E01\u0E2D\u0E38\u0E1B\u0E01\u0E23\u0E13\u0E4C\u0E01\u0E48\u0E2D\u0E19\u0E1E\u0E34\u0E21\u0E1E\u0E4C QR");await openPrintLabels(ids)}async function openPrintLabels(assetIds){const ids=(assetIds||[]).map(String).filter(Boolean);if(ids.length)try{await ensureQrLibrary();const json=await run("getAssetsForLabelsJson",ids),data=typeof json=="string"?JSON.parse(json):json;if(!data||!data.ok)throw new Error("\u0E42\u0E2B\u0E25\u0E14\u0E02\u0E49\u0E2D\u0E21\u0E39\u0E25 label \u0E44\u0E21\u0E48\u0E2A\u0E33\u0E40\u0E23\u0E47\u0E08");state.printLabels=data.labels||[],switchView("print-labels")}catch(err){toast(err.message||String(err))}}function renderPrintLabels(){const labels=state.printLabels||[];if($("labelCount").textContent=labels.length+" \u0E1B\u0E49\u0E32\u0E22 \xB7 "+(state.user?state.user.email:""),!labels.length){$("labelSheet").innerHTML='<div class="emptyTable">\u0E44\u0E21\u0E48\u0E21\u0E35 asset \u0E2A\u0E33\u0E2B\u0E23\u0E31\u0E1A\u0E1E\u0E34\u0E21\u0E1E\u0E4C \u2014 \u0E01\u0E25\u0E31\u0E1A\u0E44\u0E1B\u0E40\u0E25\u0E37\u0E2D\u0E01\u0E43\u0E19 Asset Management</div>';return}const html=labels.map(label=>{const qr=buildQrSvg(label.qr_url||"BNH-ITAM-ASSET:"+label.asset_id);return`<div class="qrLabel">
          <span class="stripe" style="background:`+escapeHtml(label.color||"#64748b")+`"></span>
          <div class="qrInner">
            <div class="qrCode">`+qr+`</div>
            <div class="qrText">
              <div class="tag">`+escapeHtml(label.asset_tag||"-")+`</div>
              <div class="meta">`+(label.serial_number?"SN: "+escapeHtml(label.serial_number):"SN: -")+`</div>
            </div>
          </div>
        </div>`}).join("");$("labelSheet").innerHTML=html,applyLabelSize()}function applyLabelSize(){const size=$("labelSize").value||"medium",sheet=$("labelSheet");sheet.classList.remove("size-small","size-medium","size-large"),sheet.classList.add("size-"+size)}function doPrintLabels(){window.print()}window.ITAM_QR_MODULE={ensureQrLibrary,buildQrSvg,renderQrInto,openQrModal,copyCurrentQrUrl,downloadCurrentQr,printCurrentQr,openPrintLabelsForSelected,openPrintLabels,renderPrintLabels,applyLabelSize,doPrintLabels}})();
